[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.21"
sha2 = "0.10"
rand = { version = "0.8", features = ["getrandom"]}
